### ISSUE TITLE
Copyright infringement 

### ISSUE THREAD

**Issue by tool-buddy** [TFS-21-22/CAPSTONE-21-22#2]
Hi,

You are distributing via your repository, and without authorization, the Unity asset called Curvy Splines, which is my copyrighted work. This puts you in an illegal position.

**Why it is illegal:**
To keep this simple, and based on the Asset Store Terms of Service and EULA:
- You are not allowed to share publicly assets you buy. See paragraph 2.2.1 for the full information.
- You are not allowed to share or use any asset categorized in "Editor Extension" (Curvy Splines being such an asset) concurrently on more than 2 different computers. Full information in the paragraph 2.3.2.

**What to do to fix:**
- Option 1: Make the repository private, while respecting the 2 computers limitation.
- Option 2: Remove Curvy Splines from you repository. Also remove it from your repository's history. Here is a guide explaining how to do that:
https://myopswork.com/how-remove-files-completely-from-git-repository-history-47ed3e0c4c35
If you are not familiar enough with git, consider training on some test repository before doing it on yours, to avoid accidentally removing something valuable to you.

**What would happen if you fail to fix this:**
I will have to request a DMCA takedown

Thanks for your time, and have a nice day

**Comment by nabayaga** [comment]
Hi! 
Thank you for letting us know. Sorry about that. We're all students new to Unity and I genuinely had no clue about this issue before I pushed it for our project. We will remove it promptly today. If we have any questions, I'll reach out to you.
Thank you for reaching out, and all the best!

**Comment by tool-buddy** [comment]
Hi Nabila
No worries, I completely understand. People share my asset on GitHub usually out of ignorance, not with malicious intent. About the actions you are going to take to resolve the issue, there is no rush, as long as you do it in a reasonable time. It can wait until next week if needed, don't want to ruin your weekend :D
Have a nice day

**Comment by Mduarte97** [comment]
Hello,

I believe we have completed the deletion and it has been removed please feel free to check for yourself see if 
we did it correct if not please let us know and we will take care of it asap!! Thank you for being so understanding with us

**Comment by tool-buddy** [comment]
Forgot to close the ticket, sorry. All the best with your projects
